style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 150
  FunctionOnlyReturningConstant:
    active: false
  ReturnCount:
    active: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  CyclomaticComplexMethod:
    active: false

naming:
  FunctionNaming:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
